# Sponsorship options for CartMax project
# Users will see these options on the GitHub repository

github: Aniket-Dev-IT
patreon: aniketkumar
ko_fi: aniketdev
buy_me_a_coffee: aniketkumar
custom: ["https://wa.me/918318601925", "https://paypal.me/aniketkumar"]
